// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqbvorvqbigzxgxvaorx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxYnZvcnZxYmlnenhneHZhb3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODEwOTEsImV4cCI6MjA1OTE1NzA5MX0.apUmRa7voxWcRJuoHKIee3NnGt9hdGCdqeHA8_SGF-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);